@startuml
'https://plantuml.com/class-diagram

class Exercise41{
    + Sorted_names: ArrayList<String>
    + Output_File: File

    - output_to_file(sorted_names)
}
class File{
    + Input_file: File
    + name: String
    + names_array: ArrayList<String>
    + Scan : Scanner

    - Read_File(File)
    - Sort_names(names)
}
Exercise41 o--> File
@enduml